import type { GraphState } from '../shared/graph'

export const defaultGraph: GraphState = {
  modules: [
    {
      id: 'osc-1',
      type: 'oscillator',
      name: 'VCO A',
      position: { x: 120, y: 140 },
      params: {
        frequency: 110,
        type: 'sawtooth',
        pwm: 0.5,
        unison: 2,
        detune: 7,
        fmLin: 0,
        fmExp: 0,
        subMix: 0,
        subOct: 1,
      },
    },
    {
      id: 'osc-2',
      type: 'oscillator',
      name: 'VCO B',
      position: { x: 320, y: 140 },
      params: {
        frequency: 110.3,
        type: 'sawtooth',
        pwm: 0.5,
        unison: 2,
        detune: 5,
        fmLin: 0,
        fmExp: 0,
        subMix: 0,
        subOct: 1,
      },
    },
    {
      id: 'lab-1',
      type: 'lab',
      name: 'Lab Panel',
      position: { x: 120, y: 560 },
      params: { level: 0.48, drive: 0.4, bias: 0, shape: 'triangle' },
    },
    {
      id: 'mix-1',
      type: 'mixer',
      name: 'Mixer 1x1',
      position: { x: 520, y: 140 },
      params: { levelA: 0.7, levelB: 0.65 },
    },
    {
      id: 'vcf-1',
      type: 'vcf',
      name: 'VCF Pro',
      position: { x: 720, y: 140 },
      params: {
        cutoff: 850,
        resonance: 0.18,
        drive: 0.1,
        envAmount: 0.35,
        modAmount: 0.18,
        keyTrack: 0.55,
        model: 'svf',
        mode: 'lp',
        slope: 12,
      },
    },
    {
      id: 'chorus-1',
      type: 'chorus',
      name: 'Chorus',
      position: { x: 940, y: 140 },
      params: {
        rate: 0.22,
        depth: 14,
        delay: 19,
        mix: 0.6,
        spread: 0.8,
        feedback: 0.14,
      },
    },
    {
      id: 'delay-1',
      type: 'delay',
      name: 'Delay',
      position: { x: 1140, y: 140 },
      params: {
        time: 420,
        feedback: 0.32,
        mix: 0.22,
        tone: 0.6,
        pingPong: true,
      },
    },
    {
      id: 'reverb-1',
      type: 'reverb',
      name: 'Reverb',
      position: { x: 1340, y: 140 },
      params: {
        time: 0.62,
        damp: 0.45,
        preDelay: 18,
        mix: 0.24,
      },
    },
    {
      id: 'gain-1',
      type: 'gain',
      name: 'VCA 1',
      position: { x: 720, y: 320 },
      params: { gain: 0.85 },
    },
    {
      id: 'mod-1',
      type: 'cv-vca',
      name: 'Mod VCA',
      position: { x: 520, y: 320 },
      params: { gain: 1 },
    },
    {
      id: 'scope-1',
      type: 'scope',
      name: 'Scope',
      position: { x: 940, y: 320 },
      params: { time: 1, gain: 1, freeze: false },
    },
    {
      id: 'out-1',
      type: 'output',
      name: 'Main Out',
      position: { x: 940, y: 500 },
      params: { level: 0.8 },
    },
    {
      id: 'adsr-1',
      type: 'adsr',
      name: 'Amp ADSR',
      position: { x: 120, y: 380 },
      params: { attack: 0.3, decay: 0.7, sustain: 0.8, release: 0.8 },
    },
    {
      id: 'adsr-2',
      type: 'adsr',
      name: 'Filter ADSR',
      position: { x: 320, y: 380 },
      params: { attack: 0.25, decay: 0.9, sustain: 0.3, release: 0.8 },
    },
    {
      id: 'lfo-1',
      type: 'lfo',
      name: 'LFO 1',
      position: { x: 520, y: 380 },
      params: { rate: 0.12, depth: 0.12, offset: 0, shape: 'sine', bipolar: true },
    },
    {
      id: 'ctrl-1',
      type: 'control',
      name: 'Control IO',
      position: { x: 720, y: 380 },
      params: {
        cv: 0,
        cvMode: 'unipolar',
        velocity: 1,
        midiVelocity: true,
        gate: 0,
        glide: 0.07,
        midiEnabled: false,
        midiChannel: 0,
        midiRoot: 60,
        midiInputId: '',
        midiVelSlew: 0.008,
        voices: 4,
        seqOn: true,
        seqTempo: 68,
        seqGate: 0.9,
      },
    },
  ],
  connections: [
    {
      from: { moduleId: 'ctrl-1', portId: 'cv-out' },
      to: { moduleId: 'osc-1', portId: 'pitch' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'ctrl-1', portId: 'cv-out' },
      to: { moduleId: 'osc-2', portId: 'pitch' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'ctrl-1', portId: 'cv-out' },
      to: { moduleId: 'vcf-1', portId: 'key' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'ctrl-1', portId: 'gate-out' },
      to: { moduleId: 'adsr-1', portId: 'gate' },
      kind: 'gate',
    },
    {
      from: { moduleId: 'ctrl-1', portId: 'gate-out' },
      to: { moduleId: 'adsr-2', portId: 'gate' },
      kind: 'gate',
    },
    {
      from: { moduleId: 'osc-1', portId: 'out' },
      to: { moduleId: 'mix-1', portId: 'in-a' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'osc-2', portId: 'out' },
      to: { moduleId: 'mix-1', portId: 'in-b' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'mix-1', portId: 'out' },
      to: { moduleId: 'vcf-1', portId: 'in' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'adsr-2', portId: 'env' },
      to: { moduleId: 'vcf-1', portId: 'env' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'lfo-1', portId: 'cv-out' },
      to: { moduleId: 'vcf-1', portId: 'mod' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'lfo-1', portId: 'cv-out' },
      to: { moduleId: 'osc-2', portId: 'pwm' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'vcf-1', portId: 'out' },
      to: { moduleId: 'gain-1', portId: 'in' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'adsr-1', portId: 'env' },
      to: { moduleId: 'mod-1', portId: 'in' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'ctrl-1', portId: 'vel-out' },
      to: { moduleId: 'mod-1', portId: 'cv' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'mod-1', portId: 'out' },
      to: { moduleId: 'gain-1', portId: 'cv' },
      kind: 'cv',
    },
    {
      from: { moduleId: 'gain-1', portId: 'out' },
      to: { moduleId: 'chorus-1', portId: 'in' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'chorus-1', portId: 'out' },
      to: { moduleId: 'delay-1', portId: 'in' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'delay-1', portId: 'out' },
      to: { moduleId: 'reverb-1', portId: 'in' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'reverb-1', portId: 'out' },
      to: { moduleId: 'scope-1', portId: 'in-a' },
      kind: 'audio',
    },
    {
      from: { moduleId: 'scope-1', portId: 'out-a' },
      to: { moduleId: 'out-1', portId: 'in' },
      kind: 'audio',
    },
  ],
}
