export const marioSongs = {
  smb: {
    name: 'Super Mario Bros',
    tempo: 180,
    ch1: [
      76, 76, null, 76, null, 72, 76, null, 79, null, null, null, 67, null, null, null,
      72, null, null, 67, null, null, 64, null, null, 69, null, 71, null, 70, 69, null,
      67, 76, 79, 81, null, 77, 79, null, 76, null, 72, 74, 71, null, null, null,
      72, null, null, 67, null, null, 64, null, null, 69, null, 71, null, 70, 69, null,
      67, 76, 79, 81, null, 77, 79, null, 76, null, 72, 74, 71, null, null, null,
    ],
    ch2: [
      64, 64, null, 64, null, 60, 64, null, 67, null, null, null, 55, null, null, null,
      60, null, null, 55, null, null, 52, null, null, 57, null, 59, null, 58, 57, null,
      55, 64, 67, 69, null, 65, 67, null, 64, null, 60, 62, 59, null, null, null,
      60, null, null, 55, null, null, 52, null, null, 57, null, 59, null, 58, 57, null,
      55, 64, 67, 69, null, 65, 67, null, 64, null, 60, 62, 59, null, null, null,
    ],
    ch3: [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    ],
    ch4: [
      36, null, null, null, 36, null, null, null, 43, null, null, null, 43, null, null, null,
      36, null, null, 43, null, null, 48, null, null, 45, null, null, null, null, null, null,
      43, null, null, null, 43, null, null, null, 48, null, null, null, 48, null, null, null,
      36, null, null, 43, null, null, 48, null, null, 45, null, null, null, null, null, null,
      43, null, null, null, 43, null, null, null, 48, null, null, null, 48, null, null, null,
    ],
    ch5: [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    ],
  },
  smw: {
    name: 'Super Mario World',
    tempo: 140,
    ch1: [
      81, 81, null, null, 77, 77, null, null, 72, 72, null, null, 74, 74, null, null,
      77, 77, null, null, 77, 77, null, null, 74, 74, null, null, 72, 72, null, null,
      77, 77, null, null, 77, 77, null, null, 84, 72, null, null, 84, null, null, null,
      81, 81, null, null, 79, 79, null, null, 72, 72, null, null, null, null, null, null,
      81, 81, null, null, 77, 77, null, null, 72, 72, null, null, 74, 74, null, null,
      77, 77, null, null, 82, 82, null, null, 81, 81, null, null, 77, 77, null, null,
    ],
    ch2: [
      81, null, 72, null, null, null, 81, null, 72, null, null, null, 81, null, 72, null,
      null, null, 81, null, 72, null, null, null, 81, null, 72, null, null, null, null, null,
      82, null, 74, null, null, null, 82, null, 74, null, null, null, 82, null, 74, null,
      null, null, 73, null, 82, null, null, null, 73, null, 82, null, null, null, null, null,
      81, null, 72, null, null, null, 81, null, 72, null, null, null, 81, null, 72, null,
      null, null, 80, null, 72, null, null, null, 81, null, 72, null, null, null, null, null,
    ],
    ch3: [
      77, null, null, null, 72, null, null, null, 67, null, null, null, 69, null, null, null,
      72, null, null, null, 72, null, null, null, 69, null, null, null, 67, null, null, null,
      72, null, null, null, 72, null, null, null, 79, null, null, null, 79, null, null, null,
      77, null, null, null, 74, null, null, null, 67, null, null, null, null, null, null, null,
      77, null, null, null, 72, null, null, null, 67, null, null, null, 69, null, null, null,
      72, null, null, null, 78, null, null, null, 77, null, null, null, 72, null, null, null,
    ],
    ch4: [
      41, null, 38, null, 43, null, 36, null, 41, null, 38, null, 44, null, 43, null,
      null, null, null, null, 45, null, 46, null, 47, null, 45, null, 44, null, 43, null,
      36, null, 38, null, 40, null, 41, null, 36, null, 40, null, 43, null, 40, null,
      36, null, 38, null, 40, null, 41, null, 43, null, 45, null, 46, null, 48, null,
      41, null, 38, null, 43, null, 36, null, 41, null, 38, null, 44, null, 43, null,
      41, null, 41, null, 39, null, 39, null, 38, null, 38, null, 37, null, 36, null,
    ],
    ch5: [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      62, null, 65, null, null, null, 67, null, 68, null, null, null, 67, null, 65, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      62, null, 60, null, null, null, 65, null, 57, null, null, null, 58, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    ],
  },
  underground: {
    name: 'Underground',
    tempo: 140,
    ch1: [
      48, null, 60, null, 55, null, 51, null, 52, null, 55, null, null, null, null, null,
      48, null, 60, null, 55, null, 51, null, 52, null, 55, null, null, null, null, null,
      51, null, 63, null, 58, null, 54, null, 55, null, 58, null, null, null, null, null,
      51, null, 63, null, 58, null, 54, null, 55, null, 58, null, null, null, null, null,
    ],
    ch2: [
      36, null, 48, null, 43, null, 39, null, 40, null, 43, null, null, null, null, null,
      36, null, 48, null, 43, null, 39, null, 40, null, 43, null, null, null, null, null,
      39, null, 51, null, 46, null, 42, null, 43, null, 46, null, null, null, null, null,
      39, null, 51, null, 46, null, 42, null, 43, null, 46, null, null, null, null, null,
    ],
    ch3: [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    ],
    ch4: [
      24, null, null, null, 24, null, null, null, 24, null, null, null, 24, null, null, null,
      24, null, null, null, 24, null, null, null, 24, null, null, null, 24, null, null, null,
      27, null, null, null, 27, null, null, null, 27, null, null, null, 27, null, null, null,
      27, null, null, null, 27, null, null, null, 27, null, null, null, 27, null, null, null,
    ],
    ch5: [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    ],
  },
} as const
