import type { ModuleSpec, ModuleType } from '../shared/graph'

export const moduleSizes: Record<ModuleType, string> = {
  oscillator: '2x3',
  supersaw: '2x2',
  'nes-osc': '2x3',
  'snes-osc': '2x3',
  noise: '2x1',
  'mod-router': '2x2',
  'sample-hold': '1x1',
  slew: '1x2',
  quantizer: '2x2',
  'ring-mod': '1x1',
  vcf: '2x2',
  hpf: '1x1',
  control: '2x6',
  scope: '2x3',
  adsr: '1x2',
  lfo: '2x2',
  chorus: '2x2',
  delay: '2x2',
  'granular-delay': '2x2',
  'tape-delay': '2x2',
  'spring-reverb': '2x1',
  reverb: '2x1',
  phaser: '2x2',
  distortion: '2x2',
  wavefolder: '2x2',
  mixer: '1x1',
  'mixer-1x2': '1x2',
  gain: '1x1',
  'cv-vca': '1x1',
  output: '1x1',
  lab: '2x2',
  mario: '2x4',
  ensemble: '2x1',
  choir: '2x2',
  vocoder: '2x3',
  'audio-in': '1x1',
  arpeggiator: '2x5',
  'step-sequencer': '3x5',
}

export const modulePortLayouts: Partial<Record<ModuleType, 'stacked' | 'strip'>> = {
  oscillator: 'strip',
  'nes-osc': 'strip',
  'snes-osc': 'strip',
  vcf: 'strip',
  control: 'strip',
  lab: 'strip',
  adsr: 'strip',
  lfo: 'strip',
  'mod-router': 'strip',
  'ring-mod': 'strip',
  vocoder: 'strip',
  mario: 'strip',
  'mixer-1x2': 'strip',
  arpeggiator: 'strip',
  'step-sequencer': 'strip',
}

export const moduleCatalog: { type: ModuleType; label: string }[] = [
  { type: 'oscillator', label: 'VCO' },
  { type: 'supersaw', label: 'Supersaw' },
  { type: 'nes-osc', label: 'NES Osc' },
  { type: 'snes-osc', label: 'SNES Osc' },
  { type: 'noise', label: 'Noise' },
  { type: 'mod-router', label: 'Mod Router' },
  { type: 'sample-hold', label: 'Sample & Hold' },
  { type: 'slew', label: 'Slew' },
  { type: 'quantizer', label: 'Quantizer' },
  { type: 'ring-mod', label: 'Ring Mod' },
  { type: 'vcf', label: 'VCF' },
  { type: 'hpf', label: 'HPF' },
  { type: 'gain', label: 'VCA' },
  { type: 'cv-vca', label: 'Mod VCA' },
  { type: 'mixer', label: 'Mixer 1x1' },
  { type: 'mixer-1x2', label: 'Mixer 1x2' },
  { type: 'chorus', label: 'Chorus' },
  { type: 'ensemble', label: 'Ensemble' },
  { type: 'choir', label: 'Choir' },
  { type: 'vocoder', label: 'Vocoder' },
  { type: 'audio-in', label: 'Audio In' },
  { type: 'delay', label: 'Delay' },
  { type: 'granular-delay', label: 'Granular Delay' },
  { type: 'tape-delay', label: 'Tape Delay' },
  { type: 'spring-reverb', label: 'Spring Reverb' },
  { type: 'reverb', label: 'Reverb' },
  { type: 'phaser', label: 'Phaser' },
  { type: 'distortion', label: 'Distortion' },
  { type: 'wavefolder', label: 'Wavefolder' },
  { type: 'adsr', label: 'ADSR' },
  { type: 'lfo', label: 'LFO' },
  { type: 'scope', label: 'Scope' },
  { type: 'control', label: 'Control IO' },
  { type: 'output', label: 'Main Out' },
  { type: 'lab', label: 'Lab' },
  { type: 'mario', label: 'Mario IO' },
  { type: 'arpeggiator', label: 'Arpeggiator' },
  { type: 'step-sequencer', label: 'Step Sequencer' },
]

export const modulePrefixes: Record<ModuleType, string> = {
  oscillator: 'osc',
  supersaw: 'ssaw',
  'nes-osc': 'nes',
  'snes-osc': 'snes',
  noise: 'noise',
  'mod-router': 'modr',
  'sample-hold': 'sh',
  slew: 'slew',
  quantizer: 'quant',
  'ring-mod': 'ring',
  vcf: 'vcf',
  hpf: 'hpf',
  gain: 'gain',
  'cv-vca': 'mod',
  mixer: 'mix',
  'mixer-1x2': 'mix2',
  chorus: 'chorus',
  ensemble: 'ens',
  choir: 'choir',
  vocoder: 'vocode',
  'audio-in': 'in',
  delay: 'delay',
  'granular-delay': 'grain',
  'tape-delay': 'tape',
  'spring-reverb': 'spring',
  reverb: 'reverb',
  phaser: 'phaser',
  distortion: 'dist',
  wavefolder: 'fold',
  adsr: 'adsr',
  lfo: 'lfo',
  scope: 'scope',
  control: 'ctrl',
  output: 'out',
  lab: 'lab',
  mario: 'mario',
  arpeggiator: 'arp',
  'step-sequencer': 'seq',
}

export const moduleLabels: Record<ModuleType, string> = {
  oscillator: 'VCO',
  supersaw: 'Supersaw',
  'nes-osc': 'NES Osc',
  'snes-osc': 'SNES Osc',
  noise: 'Noise',
  'mod-router': 'Mod Router',
  'sample-hold': 'S&H',
  slew: 'Slew',
  quantizer: 'Quantizer',
  'ring-mod': 'Ring Mod',
  vcf: 'VCF',
  hpf: 'HPF',
  gain: 'VCA',
  'cv-vca': 'Mod VCA',
  mixer: 'Mixer 1x1',
  'mixer-1x2': 'Mixer 1x2',
  chorus: 'Chorus',
  ensemble: 'Ensemble',
  choir: 'Choir',
  vocoder: 'Vocoder',
  'audio-in': 'Audio In',
  delay: 'Delay',
  'granular-delay': 'Granular Delay',
  'tape-delay': 'Tape Delay',
  'spring-reverb': 'Spring Reverb',
  reverb: 'Reverb',
  phaser: 'Phaser',
  distortion: 'Distortion',
  wavefolder: 'Wavefolder',
  adsr: 'ADSR',
  lfo: 'LFO',
  scope: 'Scope',
  control: 'Control IO',
  output: 'Main Out',
  lab: 'Lab Panel',
  mario: 'Mario IO',
  arpeggiator: 'Arpeggiator',
  'step-sequencer': 'Step Seq',
}

export const moduleDefaults: Record<ModuleType, Record<string, number | string | boolean>> = {
  oscillator: {
    frequency: 220,
    type: 'sawtooth',
    pwm: 0.5,
    unison: 1,
    detune: 0,
    fmLin: 0,
    fmExp: 0,
    subMix: 0,
    subOct: 1,
  },
  noise: { level: 0.4, noiseType: 'white' },
  'mod-router': { depthPitch: 0, depthPwm: 0, depthVcf: 0, depthVca: 0 },
  'sample-hold': { mode: 0 },
  slew: { rise: 0.05, fall: 0.05 },
  quantizer: { root: 0, scale: 0 },
  'ring-mod': { level: 0.9 },
  gain: { gain: 0.7 },
  'cv-vca': { gain: 1 },
  vcf: {
    cutoff: 800,
    resonance: 0.2,
    drive: 0.1,
    envAmount: 0,
    modAmount: 0,
    keyTrack: 0.5,
    model: 'svf',
    mode: 'lp',
    slope: 12,
  },
  hpf: {
    cutoff: 280,
  },
  mixer: { levelA: 0.6, levelB: 0.6 },
  'mixer-1x2': {
    levelA: 0.6,
    levelB: 0.6,
    levelC: 0.6,
    levelD: 0.6,
    levelE: 0.6,
    levelF: 0.6,
  },
  chorus: { rate: 0.3, depth: 8, delay: 18, mix: 0.4, spread: 0.6, feedback: 0.1 },
  ensemble: { rate: 0.25, depth: 12, delay: 12, mix: 0.6, spread: 0.7 },
  choir: { vowel: 0, rate: 0.25, depth: 0.35, mix: 0.5 },
  vocoder: {
    attack: 25,
    release: 140,
    low: 120,
    high: 5000,
    q: 2.5,
    formant: 0,
    emphasis: 0.4,
    unvoiced: 0.0,
    mix: 0.8,
    modGain: 1,
    carGain: 1,
  },
  'audio-in': { gain: 1 },
  delay: { time: 360, feedback: 0.25, mix: 0.2, tone: 0.6, pingPong: false },
  'granular-delay': {
    time: 420,
    size: 120,
    density: 6,
    pitch: 1,
    feedback: 0.35,
    mix: 0.5,
  },
  'tape-delay': {
    time: 420,
    feedback: 0.35,
    mix: 0.35,
    tone: 0.55,
    wow: 0.2,
    flutter: 0.2,
    drive: 0.2,
  },
  'spring-reverb': {
    decay: 0.6,
    tone: 0.4,
    mix: 0.4,
    drive: 0.2,
  },
  reverb: { time: 0.6, damp: 0.4, preDelay: 18, mix: 0.2 },
  phaser: { rate: 0.5, depth: 0.7, feedback: 0.3, mix: 0.5 },
  distortion: { drive: 0.5, tone: 0.5, mix: 1.0, mode: 'soft' },
  wavefolder: { drive: 0.4, fold: 0.5, bias: 0, mix: 0.8 },
  supersaw: { frequency: 220, detune: 25, mix: 1.0 },
  'nes-osc': {
    frequency: 220,
    fine: 0,
    volume: 1.0,
    mode: 0,      // 0=Pulse1, 1=Pulse2, 2=Triangle, 3=Noise
    duty: 1,      // 0=12.5%, 1=25%, 2=50%, 3=75%
    noiseMode: 0, // 0=Random, 1=Loop
    bitcrush: 1.0,
  },
  'snes-osc': {
    frequency: 220,
    fine: 0,
    volume: 1.0,
    wave: 0,      // 0-7 wavetable selection
    gauss: 0.7,   // Gaussian filter intensity
    color: 0.5,   // Brightness
    lofi: 0.5,    // 32kHz decimation effect
  },
  adsr: { attack: 0.02, decay: 0.2, sustain: 0.65, release: 0.5 },
  lfo: { rate: 0.5, depth: 0.6, offset: 0, shape: 'sine', bipolar: true },
  scope: { time: 1, gain: 1, freeze: false },
  control: {
    cv: 0,
    cvMode: 'unipolar',
    velocity: 1,
    midiVelocity: true,
    gate: 0,
    glide: 0.02,
    midiEnabled: false,
    midiChannel: 0,
    midiRoot: 60,
    midiInputId: '',
    midiVelSlew: 0.008,
    voices: 4,
    seqOn: false,
    seqTempo: 90,
    seqGate: 0.6,
  },
  output: { level: 0.8 },
  lab: { level: 0.5, drive: 0.3, bias: 0, shape: 'triangle' },
  mario: { running: false, tempo: 180, song: 'smb' },
  arpeggiator: {
    enabled: true,
    hold: false,
    mode: 0,           // 0=UP, 1=DOWN, 2=UP_DOWN, etc.
    octaves: 1,
    rate: 7,           // 1/8 note
    gate: 75,          // 75% gate length
    swing: 0,
    tempo: 120,
    ratchet: 1,
    ratchetDecay: 0,
    probability: 100,
    velocityMode: 0,   // 0=FIXED
    accentPattern: 0,  // 0=OFF
    euclidSteps: 8,
    euclidFill: 4,
    euclidRotate: 0,
    euclidEnabled: false,
    mutate: 0,
    preset: 0,
  },
  'step-sequencer': {
    enabled: true,
    tempo: 120,
    rate: 9,           // 1/16 note
    gateLength: 50,    // 50% gate
    swing: 0,
    slideTime: 50,     // 50ms slide
    length: 16,        // 16 steps
    direction: 0,      // 0=FWD, 1=REV, 2=PINGPONG, 3=RANDOM
    stepData: JSON.stringify([
      { pitch: 0, gate: true, velocity: 100, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
      { pitch: 0, gate: true, velocity: 80, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
      { pitch: 0, gate: true, velocity: 100, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
      { pitch: 0, gate: true, velocity: 80, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
      { pitch: 0, gate: true, velocity: 100, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
      { pitch: 0, gate: true, velocity: 80, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
      { pitch: 0, gate: true, velocity: 100, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
      { pitch: 0, gate: true, velocity: 80, slide: false },
      { pitch: 0, gate: false, velocity: 100, slide: false },
    ]),
  },
}

export const getNextModuleIndex = (type: ModuleType, modules: ModuleSpec[]) => {
  const prefix = `${modulePrefixes[type]}-`
  let maxIndex = 0
  modules.forEach((module) => {
    if (!module.id.startsWith(prefix)) {
      return
    }
    const suffix = Number(module.id.slice(prefix.length))
    if (Number.isFinite(suffix)) {
      maxIndex = Math.max(maxIndex, suffix)
    }
  })
  return maxIndex + 1
}

export const buildModuleSpec = (type: ModuleType, modules: ModuleSpec[]): ModuleSpec => {
  const index = getNextModuleIndex(type, modules)
  const label = moduleLabels[type]
  const name = index === 1 ? label : `${label} ${index}`
  return {
    id: `${modulePrefixes[type]}-${index}`,
    type,
    name,
    position: { x: 0, y: 0 },
    params: { ...moduleDefaults[type] },
  }
}
